/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppdb;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JTable;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
/**
 *
 * @author USER
 */

public class form_transaksi extends javax.swing.JFrame {
DefaultTableModel model1;

    /**
     * Creates new form form_transaksi
     */
    public form_transaksi() {
      initComponents();
        String[] judul = {"NIS", "NT", "NAMA", "PEMBAYARAN", "BIAYA","TINGKAT"};
        model1 = new DefaultTableModel(judul, 0);
        tabel1.setModel(model1);
        tampilkan();

        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
    }

    private void tabelMouseClicked(MouseEvent evt) {
         int barisTerpilih = tabel1.getSelectedRow();
    
    if (barisTerpilih >= 0) {
        // Mengambil nilai dari kolom pada baris yang diklik
        String nis = model1.getValueAt(barisTerpilih, 0).toString();
        String nt = model1.getValueAt(barisTerpilih, 1).toString();
        String nama = model1.getValueAt(barisTerpilih, 2).toString();
        String tingkat = model1.getValueAt(barisTerpilih, 3).toString();
        String pembayaran = model1.getValueAt(barisTerpilih, 4).toString();
        String biaya = model1.getValueAt(barisTerpilih, 5).toString();
        
        // Menampilkan nilai dari tabel ke dalam teks field
        tfNIS.setText(nis);
        tfNT.setText(nt);
        tfNAMA.setText(nama);
        comboTingkat.setSelectedItem(tingkat);
        comboJK.setSelectedItem(pembayaran);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNIS = new javax.swing.JTextField();
        buttonSelesai = new javax.swing.JButton();
        tfNT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        comboJK = new javax.swing.JComboBox<>();
        tfNAMA = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        tfBIAYA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboTingkat = new javax.swing.JComboBox<>();
        buttonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNISActionPerformed(evt);
            }
        });

        buttonSelesai.setText("SELESAI");
        buttonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelesaiActionPerformed(evt);
            }
        });

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "NO.TRANSAKI", "NAMA", "TINGKAT", "PEMBAYARAN", "BIAYA"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        comboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "TRANSFER", "TELLER", "CASH", " " }));
        comboJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJKActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel8.setText("~~~FORM TRANSAKSI~~~");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(222, 222, 222))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setText("NOMOR INDUK SISWA");

        jLabel2.setText("NOMOR TRANSAKSI");

        jLabel3.setText("NAMA");

        jLabel4.setText("PEMBAYARAN");

        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel7.setText("BIAYA");

        buttonEdit.setText("EDIT");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        tfBIAYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBIAYAActionPerformed(evt);
            }
        });

        jLabel5.setText("TINGKAT");

        comboTingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "SD", "SMP", "SMA" }));
        comboTingkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTingkatActionPerformed(evt);
            }
        });

        buttonClear.setText("CLEAR");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfBIAYA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNT, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEdit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboJK, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSelesai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonHapus, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonClear)
                                    .addComponent(buttonSimpan))))
                        .addGap(60, 60, 60))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(buttonSimpan)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClear)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(comboJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfBIAYA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(comboTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSelesai)))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJKActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        {            
    String nis = tfNIS.getText();
    String nt = tfNT.getText();
    String nama = tfNAMA.getText();
    String pembayaran = (String) comboJK.getSelectedItem();
    String biaya = tfBIAYA.getText();
    String tingkat = (String) comboTingkat.getSelectedItem();
   

    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb-db", "root", "");
        String sql = "INSERT INTO formtransaksi (NIS, NT, NAMA,TINGKAT ,PEMBAYARAN, BIAYA) VALUES (?, ?, ?, ?, ?,?)";
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, nis);
        pst.setString(2, nt);
        pst.setString(3, nama);
        pst.setString(4, tingkat);
        pst.setString(5, pembayaran);
        pst.setString(6, biaya);

        int affectedRows = pst.executeUpdate();
        if (affectedRows > 0) {
            JOptionPane.showMessageDialog(this, "Data transaksi berhasil disimpan ke database");
            tampilkan(); // Refresh tabel setelah penyimpanan berhasil
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data transaksi ke database");
        }

        pst.close();
        cn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + ex.getMessage());
        Logger.getLogger(form_transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNISActionPerformed

    private void comboTingkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTingkatActionPerformed
    switch (comboTingkat.getSelectedIndex()) {
        case 0: tfBIAYA.setText(""); break;
        case 1: tfBIAYA.setText("5000000"); break;
        case 2: tfBIAYA.setText("7000000"); break;
        case 3: tfBIAYA.setText("10000000"); break;
/// TODO add your handling code here:
    }//GEN-LAST:event_comboTingkatActionPerformed
    }
    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        {
    int barisTerpilih = tabel1.getSelectedRow();

    if (barisTerpilih >= 0) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            String nis = model1.getValueAt(barisTerpilih, 0).toString();
            String nt = model1.getValueAt(barisTerpilih, 1).toString();
            
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb-db", "root", "");
                String sql = "DELETE FROM formtransaksi WHERE NIS=? AND NT=?";
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, nis);
                pst.setString(2, nt);

                int deletedRows = pst.executeUpdate();
                if (deletedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Data transaksi berhasil dihapus dari database");
                    tampilkan(); // Refresh tabel setelah penghapusan berhasil
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data transaksi dari database");
                }

                pst.close();
                cn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + ex.getMessage());
                Logger.getLogger(form_transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus terlebih dahulu");
    }
}
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tfBIAYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBIAYAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBIAYAActionPerformed

    private void buttonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelesaiActionPerformed
          {
    form_awal buttonSelesai = new form_awal();
    
    // Menampilkan form_siswa
    buttonSelesai.setVisible(true);
    
    // Menyembunyikan form_awal jika diperlukan
    this.setVisible(false);
}            // TODO add your handling code here:
    }//GEN-LAST:event_buttonSelesaiActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
            {      
                 int barisTerpilih = tabel1.getSelectedRow();

    if (barisTerpilih >= 0) {
        String nis = tfNIS.getText();
        String nt = tfNT.getText();
        String nama = tfNAMA.getText();
        String pembayaran = (String) comboJK.getSelectedItem();
        String biaya = tfBIAYA.getText();
        String tingkat = (String) comboTingkat.getSelectedItem();

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb-db", "root", "");
            String sql = "UPDATE formtransaksi SET NIS=?, NT=?, NAMA=?, TINGKAT=?, PEMBAYARAN=?, BIAYA=? WHERE NIS=? AND NT=?";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, nis);
            pst.setString(2, nt);
            pst.setString(3, nama);
            pst.setString(4, tingkat);
            pst.setString(5, pembayaran);
            pst.setString(6, biaya);
            pst.setString(7, model1.getValueAt(barisTerpilih, 0).toString());
            pst.setString(8, model1.getValueAt(barisTerpilih, 1).toString());

            int updatedRows = pst.executeUpdate();
            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data transaksi berhasil diubah");
                tampilkan(); // Refresh tabel setelah pengubahan berhasil
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data transaksi");
            }

            pst.close();
            cn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + ex.getMessage());
            Logger.getLogger(form_transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diubah terlebih dahulu");
    }
            }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
     {                                            
    tfNIS.setText("");
    tfNT.setText("");
    tfNAMA.setText("");
    comboJK.setSelectedIndex(0);
    tfBIAYA.setText("");
    comboTingkat.setSelectedIndex(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSelesai;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> comboJK;
    private javax.swing.JComboBox<String> comboTingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tfBIAYA;
    private javax.swing.JTextField tfNAMA;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNT;
    // End of variables declaration//GEN-END:variables
    private void tampilkan() {
        int row = model1.getRowCount();
        for (int a = row - 1; a >= 0; a--) {
            model1.removeRow(a);
        }

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ppdb-db", "root", "");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM formtransaksi");

            while (rs.next()) {
                String data[] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)};
                model1.addRow(data);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + ex.getMessage());
            Logger.getLogger(form_siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
